services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cafedb
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    security_opt:
      - "apparmor:unconfined"

volumes:
  postgres_data_volume: